export const TASK_CONSTANTS = {
    GET_ALL: "GET_TALL",
    SEARCH: "SEARCH",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    ADD_TASK: "ADD_TASK",
    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    DELETE_TASK: "DELETE_TASK",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    UPDATE_TASK: "UPDATE_TASK",
    UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
}